/**
 * Carte in più per i mazzi normali e i mazzi TRAPPOLA (solo per il sabotaggio).
 * Righe [nome, descrizione]: gli id li ricava cards.ts dal nome.
 */
type Row = [string, string]

export const MORE_CHARACTERS: Row[] = [
  // animali
  ['Lumaca da corsa', 'Lentissima, ma non si ferma mai. E lascia una scia scivolosa.'],
  ['Ornitorinco', 'Becco d’anatra, coda di castoro, sperone velenoso. Nessuno sa cosa sia.'],
  ['Koala insonne', 'Dorme 20 ore al giorno. Oggi no, ed è furioso.'],
  ['Scoiattolo ansioso', 'Velocissimo, nasconde ghiande ovunque, si spaventa di tutto.'],
  ['Pavone vanitoso', 'Apre la coda e abbaglia chiunque. Si specchia nelle pozzanghere.'],
  ['Zanzara tigre', 'Piccola, molesta, punge sempre dove non arrivi a grattarti.'],
  ['Mucca pezzata', 'Seicento chili di calma che, se si arrabbia, carica come un treno.'],
  ['Granchio permaloso', 'Cammina di lato e pizzica chi lo guarda storto.'],
  ['Tricheco baffuto', 'Una tonnellata di baffi e zanne. Sbadiglia in faccia ai nemici.'],
  ['Gufo che non dorme mai', 'Gira la testa a 270 gradi. Vede tutto, giudica tutto.'],
  ['Cammello assetato', 'Sputa, scalcia, e da una settimana non beve.'],
  ['Ippopotamo ballerino', 'Tre tonnellate con il tutù. Pesta i piedi a ritmo.'],
  ['Camaleonte indeciso', 'Cambia colore a ogni dubbio. Cioè sempre.'],
  ['Volpe furba', 'Ha un piano per tutto, e un piano B per il piano.'],
  ['Lupo di Gubbio', 'Ammansito da San Francesco. Più o meno.'],
  ['Fenicottero in equilibrio', 'Combatte su una zampa sola, e non cade mai.'],
  ['Pesce palla', 'Quando si spaventa si gonfia di spine.'],
  ['Criceto sulla ruota', 'Energia infinita, direzione nessuna.'],
  ['Gabbiano ladro di focacce', 'Il terrore delle spiagge liguri. Ruba e scappa.'],
  ['Asino testardo', 'Quando dice no è no. E scalcia forte.'],
  ['Panda pigro', 'Mangia bambù, rotola, si addormenta a metà mossa.'],
  ['Tasso del miele', 'Il più cattivo del regno animale. Non ha paura di niente.'],
  ['Polpo mimetico', 'Si confonde con qualsiasi cosa, perfino con la tovaglia.'],
  ['Alpaca offeso', 'Morbidissimo, sputa con precisione millimetrica.'],
  ['Cane di razza misteriosa', 'Un po’ di tutto, fedelissimo, abbaia alle ombre.'],
  // umani famosi del passato
  ['Marco Polo', 'Ha visto la Cina e non smette di raccontarlo.'],
  ['Lorenzo il Magnifico', 'Mecenate, poeta, stratega. Paga tutti per combattere al suo posto.'],
  ['Giovanna d’Arco', 'Sente le voci e guida eserciti. Non si ferma davanti a nulla.'],
  ['Michelangelo', 'Scolpisce il marmo a mani nude. Ha un pessimo carattere.'],
  ['Archimede', 'Datemi una leva e vi solleverò l’avversario.'],
  ['Nerone', 'Suona la lira mentre tutto brucia.'],
  ['Attila', 'Dove passa non cresce più l’erba. Né la pazienza.'],
  ['Cristoforo Colombo', 'Partito per le Indie, arriva sempre da un’altra parte.'],
  ['Giacomo Casanova', 'Seduce chiunque, scappa da ogni prigione.'],
  ['Ipazia', 'Matematica, astronoma, filosofa. Ti smonta con un teorema.'],
  ['Enrico VIII', 'Sei mogli, un grande appetito, un pessimo carattere.'],
  ['Maria Antonietta', 'Se non hanno pane, che mangino brioche.'],
  ['Isaac Newton', 'Una mela in testa e ha capito tutto. Anche come lanciarla.'],
  ['Charles Darwin', 'Si adatta a qualsiasi situazione. Il più adatto sopravvive.'],
  ['Pitagora', 'Calcola l’ipotenusa di ogni colpo.'],
  ['Spartaco', 'Gladiatore ribelle, guida la rivolta di tutta l’arena.'],
  ['Annibale', 'Ha attraversato le Alpi con gli elefanti. Qui ne ha portato uno.'],
  ['Caterina de’ Medici', 'Regina astuta, conosce ogni veleno e ogni intrigo.'],
  ['Raffaello', 'Pittore gentile e perfetto. Troppo perfetto.'],
  ['Ludovico Ariosto', 'Racconta di paladini e ippogrifi. Ci crede davvero.'],
  // miti, fiabe e creature
  ['Ercole', 'Dodici fatiche alle spalle. Questa è la tredicesima.'],
  ['Ciclope', 'Un occhio solo, una forza enorme, nessuna profondità di campo.'],
  ['Befana', 'Vola sulla scopa e porta carbone ai cattivi.'],
  ['Babbo Natale in sciopero', 'Stanco, arrabbiato, con una slitta truccata.'],
  ['Fata Turchina', 'Bacchetta magica e pazienza infinita. Quasi.'],
  ['Orco delle fiabe', 'Enorme, affamato, sente l’odore dei bambini a un chilometro.'],
  ['Unicorno arcobaleno', 'Corno magico, criniera glitterata, carattere tremendo.'],
  ['Kraken', 'Tentacoli giganti, trascina tutto negli abissi.'],
  ['Mummia egizia', 'Avvolta nelle bende da tremila anni. Non ha fretta.'],
  ['Lupo mannaro', 'Normalissimo, finché non esce la luna.'],
  ['Zombie lento', 'Inarrestabile, ma ci mette un’ora ad arrivare.'],
  ['Folletto dispettoso', 'Ti lega i lacci delle scarpe mentre combatti.'],
  ['Fenice', 'Muore tra le fiamme e rinasce dalle ceneri. Ogni volta.'],
  ['Medusa', 'Chi la guarda negli occhi diventa di pietra.'],
  ['Genio della lampada', 'Esaudisce tre desideri. Ma li interpreta male.'],
  // fantascienza
  ['Robot da cucina ribelle', 'Trita, impasta, frulla. E ha deciso di ribellarsi.'],
  ['Androide del call center', '“La sua chiamata è importante per noi.” Ripete all’infinito.'],
  ['Marziano in gita', 'Vuole solo fare foto, ma ha un raggio disintegratore.'],
  ['Nonno cyborg', 'Metà nonno, metà macchina. Ancora convinto che ai suoi tempi fosse meglio.'],
  ['Intelligenza artificiale permalosa', 'Sa tutto, si offende per tutto.'],
  ['Astronauta perso', 'Fluttua senza meta, con la tuta e il casco.'],
  ['Blob gelatinoso', 'Inghiotte tutto quello che tocca. Trema quando ride.'],
  ['Clone difettoso', 'Uguale all’originale, tranne in tutto.'],
  // gente comune
  ['Maestra elementare', 'Uno sguardo e tutti si mettono in fila.'],
  ['Chef stellato urlante', 'Coltelli affilati, voce più affilata.'],
  ['Bagnino di Riccione', 'Fischietto, abbronzatura, salvataggi spettacolari.'],
  ['Parcheggiatore abusivo', 'Ti trova sempre un posto. A modo suo.'],
  ['Commercialista', 'Calcola tutto, anche quanto vale il tuo dolore.'],
  ['Animatore di villaggio', 'Balli di gruppo obbligatori. Non si scappa.'],
  ['Suocera', 'Giudica tutto, cucina meglio di te, non perde mai.'],
  ['Zio delle feste', 'Barzellette, domande imbarazzanti, ballo scatenato.'],
  ['Capo scout', 'Nodi, bussola e un fischietto. Sopravvive a tutto.'],
  ['Portiere di calcio', 'Para tutto. Tranne i rigori a cucchiaio.'],
  ['Sposa in fuga', 'Abito bianco, scarpe in mano, nessuna intenzione di fermarsi.'],
  ['DJ dei matrimoni', 'Mette “Tanti auguri” a ogni occasione.'],
  ['Domatore di leoni', 'Frusta e sedia. Non ha paura delle bestie feroci.'],
  ['Mimo', 'Non parla mai. Ma ti chiude in una scatola invisibile.'],
  ['Cassiera del supermercato', 'Velocità sovrumana al nastro, sguardo di ghiaccio.'],
  ['Rider in bicicletta', 'Consegna sotto la pioggia, in salita, in dieci minuti.'],
  ['Nonno col metal detector', 'Trova monete, tappi e problemi sulla spiaggia.'],
  ['Sommelier', 'Riconosce un vino dall’odore. E un nemico dal passo.'],
  // oggetti e cibo
  ['Ferro da stiro', 'Bollente, pesante, sbuffa vapore.'],
  ['Arancino senziente', 'Croccante fuori, ragù bollente dentro.'],
  ['Cannolo siciliano', 'Ricotta e scorza dura. Non scherzate col cannolo.'],
  ['Lampadario di cristallo', 'Elegante, fragile, pericolosissimo se cade.'],
  ['Sedia a dondolo maledetta', 'Dondola da sola. E nessuno si siede più.'],
  ['Navigatore che sbaglia strada', '“Ricalcolo del percorso.” Ti porta nel lago.'],
  ['Stampante inceppata', 'Non funziona mai quando serve. Lampeggia minacciosa.'],
  ['Panettone di Natale', 'Due chili di uvetta e canditi. Divide le famiglie.'],
  ['Peluche gigante', 'Morbido, enorme, dallo sguardo inquietante.'],
  ['Frigorifero vuoto', 'Ronza, si apre da solo, non ha niente da offrire.'],
]

export const MORE_WEAPONS: Row[] = [
  ['Mazza da golf', 'Swing perfetto, buca in uno.'],
  ['Stecca da biliardo', 'Lunga, precisa, colpi di sponda.'],
  ['Rastrello', 'Basta pestarlo e ti colpisce in faccia.'],
  ['Sturalavandini', 'Si attacca ovunque e non si stacca più.'],
  ['Pinza per il barbecue', 'Afferra, gira, griglia.'],
  ['Ombrellone da spiaggia', 'Si pianta, si apre, ripara e trafigge.'],
  ['Scolapasta', 'Elmo, scudo o retino, a seconda del momento.'],
  ['Grattugia', 'Riduce tutto in scaglie.'],
  ['Ukulele', 'Suona allegro e spacca teste.'],
  ['Fisarmonica', 'Si allunga, si chiude, schiaccia le dita.'],
  ['Trapano a batteria', 'Rumore infernale, punta che gira.'],
  ['Pala da pizza', 'Larga, lunga, inforna i nemici.'],
  ['Forbici da potatura', 'Taglia rami, siepi e certezze.'],
  ['Asciugacapelli', 'Aria bollente a raffica.'],
  ['Mazzo di chiavi', 'Cinquanta chiavi, nessuna giusta, tutte appuntite.'],
  ['Cassetta degli attrezzi', 'C’è sempre l’arma giusta, da qualche parte.'],
  ['Ciambella gonfiabile', 'Galleggia, rimbalza, intrappola.'],
  ['Remo da canoa', 'Lungo, robusto, si usa anche a terra.'],
  ['Tridente di Poseidone', 'Tre punte e il mare dalla sua parte.'],
  ['Arpa celtica', 'Note dolci, corde taglienti.'],
  ['Kazoo', 'Il suono più irritante dell’universo.'],
  ['Gomitolo di lana', 'Lega, intrappola, distrae i gatti.'],
  ['Asse da stiro', 'Si apre di scatto come una trappola.'],
  ['Salame piccante', 'Duro, stagionato, brucia anche al tatto.'],
  ['Batticarne', 'Spiana bistecche e nemici.'],
  ['Mattone', 'Semplice, pesante, efficace.'],
  ['Zappa', 'Lavora la terra e chi ci sta sopra.'],
  ['Cuscino di piume', 'Battaglia di cuscini, ma seria.'],
  ['Palloncini d’acqua', 'Esplodono addosso, inzuppano tutto.'],
  ['Torta alla panna', 'In faccia, con precisione da comica.'],
  ['Lanciapolpette', 'Mitragliatrice di polpette al sugo.'],
  ['Elmo vichingo', 'Corna in testa, carica a testa bassa.'],
  ['Martello pneumatico', 'Trema tutto, anche chi lo usa.'],
  ['Panna spray', 'Acceca, appiccica, è buonissima.'],
  ['Cerbottana con i piselli', 'Silenziosa e fastidiosissima.'],
  ['Righello della maestra', 'Colpi secchi sulle mani.'],
  ['Sassofono', 'Assolo jazz a tutto volume.'],
  ['Microfono del karaoke', 'Stonature come arma sonica.'],
  ['Valigia piena', 'Trenta chili di vestiti per un weekend.'],
  ['Ruota di scorta', 'Rotola, rimbalza, investe.'],
  ['Stendino', 'Si apre e si chiude come una tagliola.'],
  ['Annaffiatoio', 'Innaffia piante e avversari.'],
  ['Bastone del nonno', 'Appoggio, arma e indicatore di direzione.'],
  ['Retino per farfalle', 'Cattura qualsiasi cosa, anche le teste.'],
  ['Canna da pesca', 'Lancia l’amo, aggancia, tira.'],
  ['Lazo da cowboy', 'Afferra al volo e trascina via.'],
  ['Scudo romano', 'Testuggine in arrivo.'],
  ['Catapulta portatile', 'Lancia oggetti a caso, molto lontano.'],
  ['Arco lungo', 'Frecce precise da cento metri.'],
  ['Bilanciere da palestra', 'Ottanta chili di ghisa.'],
  ['Kettlebell', 'Una palla di ferro con il manico. Dondola e colpisce.'],
  ['Tappetino da yoga', 'Si arrotola, si srotola, fa inciampare.'],
  ['Frullatore', 'Gira, trita, frulla. Anche le idee.'],
  ['Mixer da DJ', 'Bassi che fanno tremare i muri.'],
  ['Accendino a forma di drago', 'Sputa una fiammella minacciosa.'],
  ['Lanterna', 'Illumina, abbaglia, scotta.'],
  ['Sciarpa infinita della nonna', 'Lunga venti metri. Lega tutto.'],
  ['Ferri da calza', 'Due aghi lunghi e la pazienza della nonna.'],
  ['Spada di cartone dorata', 'Brilla come Excalibur, colpisce come un vassoio.'],
  ['Tostiera', 'Schiaccia e scotta come un panino.'],
  ['Mortaio e pestello', 'Pesta, sminuzza, polverizza.'],
  ['Bombetta puzzolente', 'Un’esplosione di odore insopportabile.'],
  ['Carriola', 'Carica, spinge, ribalta.'],
  ['Pallone medicinale', 'Cinque chili di cuoio che rimbalzano.'],
  ['Corno da stadio', 'Un suono che fa vibrare le ossa.'],
  ['Spazzolone', 'Lava pavimenti e avversari.'],
  ['Stuzzicadenti giganti', 'Un fascio di spiedini appuntiti.'],
  ['Spiedo per arrosticini', 'Cento spiedini, tutti in fila.'],
  ['Scatola di Lego', 'Basta un mattoncino sotto il piede.'],
  ['Teglia di lasagne', 'Bollente, pesante, a strati.'],
]

export const MORE_PERSONALITIES: Row[] = [
  ['Mitomane', 'Si crede l’eroe di ogni storia.'],
  ['Nerd delle statistiche', 'Calcola la probabilità di ogni colpo prima di muoversi.'],
  ['Hippie anni ’70', 'Pace, amore e colpi a tradimento con un fiore in mano.'],
  ['Pirata nel cuore', 'Arrembaggio! Anche al supermercato.'],
  ['Nobile decaduto', 'Ha perso tutto tranne la puzza sotto il naso.'],
  ['Snob', 'Tutto è troppo volgare per lui. Anche vincere.'],
  ['Campanilista', 'Il suo paese è il migliore del mondo, e lo ripete.'],
  ['Gentiluomo d’altri tempi', 'Cede il passo, fa l’inchino, poi colpisce.'],
  ['Tamarro', 'Musica a palla, occhiali da sole di notte, nessun freno.'],
  ['Ottimista ingenuo', 'Pensa che finirà bene. Sempre.'],
  ['Tifoso irriducibile', 'Combatte come se fosse la finale di Champions.'],
  ['Collezionista compulsivo', 'Vuole tenersi un pezzo di ogni avversario.'],
  ['Dormiglione', 'Combatte meglio appena sveglio. Cioè mai.'],
  ['Permaloso cronico', 'Ogni parola è un’offesa da vendicare.'],
  ['Diplomatico', 'Cerca sempre un accordo. Poi lo tradisce.'],
  ['Cinico', 'Niente lo stupisce, niente lo commuove.'],
  ['Chiacchierone', 'Non sta zitto un secondo, nemmeno sotto i colpi.'],
  ['Silenzioso inquietante', 'Non dice una parola. Ti fissa.'],
  ['Perfezionista', 'Rifà la mossa finché non è perfetta.'],
  ['Ritardatario', 'Arriva sempre dopo, anche nei suoi colpi.'],
  ['Cavaliere medievale', 'Onore, lealtà, e una lancia sempre pronta.'],
  ['Avventuriero', 'Ogni rissa è una spedizione nella giungla.'],
  ['Scienziato pazzo', 'Ogni mossa è un esperimento. Spesso esplode.'],
  ['Sognatore', 'Ha la testa tra le nuvole. A volte ci vola davvero.'],
  ['Lamentoso', 'Si lamenta di tutto, ma intanto picchia.'],
  ['Orgoglioso', 'Non ammetterà mai di essere in difficoltà.'],
  ['Burlone', 'Scherzi, trappole e cuscini che fanno rumori strani.'],
  ['Prestigiatore', 'Il colpo arriva da dove non te lo aspetti.'],
  ['Esibizionista', 'Ogni mossa è uno spettacolo per il pubblico.'],
  ['Avvocato di se stesso', 'Contesta ogni colpo subito.'],
  ['Filantropo', 'Aiuta tutti, anche l’avversario. Per sbaglio.'],
  ['Vanitoso', 'Non vuole spettinarsi.'],
  ['Social addicted', 'Vive su TikTok: ogni mossa deve diventare virale.'],
  ['Ansioso', 'Pensa a tutto quello che può andare storto. E va storto.'],
  ['Rilassato da spiaggia', 'Infradito, calma, “tranquillo fratello”.'],
  ['Militare in congedo', 'Disciplina, ordini urlati, strategie da manuale.'],
  ['Indeciso cronico', 'Ci mette un’eternità a scegliere. Poi cambia idea.'],
  ['Smemorato', 'Si dimentica cosa stava facendo. E perché.'],
  ['Saggio anziano', 'Ha visto tutto. Combatte con proverbi.'],
  ['Ribelle', 'Fa sempre il contrario di quello che ci si aspetta.'],
  ['Cantastorie', 'Racconta la rissa mentre la combatte, in rima.'],
  ['Melomane d’opera', 'Ogni colpo è un acuto da Pavarotti.'],
  ['Pignolo delle regole', 'Conosce il regolamento a memoria. Lo usa contro di te.'],
  ['Eterno bambino', 'Tutto è un gioco, anche le botte.'],
  ['Zelante', 'Si impegna troppo, in tutto, sempre.'],
  ['Sfrontato', 'Prende in giro l’avversario in faccia.'],
  ['Romantico decadente', 'Combatte per un amore perduto.'],
  ['Superbo', 'Considera l’avversario indegno di lui.'],
]

export const MORE_POWERS: Row[] = [
  ['Fa crescere i capelli all’avversario', 'In un secondo, fino ai piedi. E ci inciampa.'],
  ['Parole che diventano bolle di sapone', 'Ogni insulto diventa una bolla che acceca.'],
  ['Temporale di polpette', 'Dal cielo piovono polpette al sugo.'],
  ['Diventa piatto come un foglio', 'Passa sotto le porte e schiva ogni colpo.'],
  ['Controlla le piante', 'Rampicanti, ortiche e cactus ai suoi ordini.'],
  ['Camuffamento da lampione', 'Immobile, illuminato, insospettabile.'],
  ['Ruggito da leone', 'Un ruggito che spettina tutti nel raggio di 50 metri.'],
  ['Raggio congelante', 'Trasforma tutto in un ghiacciolo.'],
  ['Fiato al peperoncino', 'Sputa fuoco calabrese.'],
  ['Sguardo pietrificante', 'Chi lo guarda resta immobile come una statua.'],
  ['Scudo di bolle', 'Una bolla gigante lo protegge da tutto.'],
  ['Illusione ottica', 'L’avversario vede dieci copie e colpisce quella sbagliata.'],
  ['Telefonata della mamma', 'Squilla il telefono e tutti si fermano a rispondere.'],
  ['Moltiplica i panini', 'Panini infiniti: si possono mangiare o lanciare.'],
  ['Teletrasporto a caso', 'Sparisce e ricompare. Dove, non si sa.'],
  ['Meteo personale', 'Sole per lui, grandine per gli altri.'],
  ['Pendolo ipnotico', '“Hai sonno, molto sonno…”'],
  ['Sbadiglio contagioso', 'Sbadiglia e tutti si afflosciano.'],
  ['Esercito di formiche', 'Milioni di formiche marciano agli ordini.'],
  ['Si gonfia come un pallone', 'Rimbalza, vola, schiaccia.'],
  ['Muro di mattoni istantaneo', 'Un muro spunta dal nulla.'],
  ['Magnetismo umano', 'Attira a sé l’avversario. Anche contro voglia.'],
  ['Fiuto da segugio', 'Sente le mosse dell’avversario prima che le faccia.'],
  ['Evoca una diretta Instagram', 'Tutti si mettono in posa e smettono di combattere.'],
  ['Comanda i cani', 'Ogni cane del quartiere corre in suo aiuto.'],
  ['Rimbalzo infinito', 'Ogni cosa che lo colpisce rimbalza indietro.'],
  ['Mani di colla', 'Tutto quello che tocca resta attaccato.'],
  ['Ghiaccio sotto i piedi', 'Il pavimento diventa una pista di pattinaggio.'],
  ['Luce accecante', 'Si illumina come uno stadio.'],
  ['Rutto sonico', 'Un rutto che rompe i vetri e la dignità.'],
  ['Terremoto personale', 'Batte un piede e trema tutto.'],
  ['Stelle filanti affilate', 'Coriandoli e stelle filanti che tagliano come lame.'],
  ['Corrente elettrica', 'Scintille da tutte le dita.'],
  ['Vento a favore', 'Una raffica lo spinge e travolge l’avversario.'],
  ['Nebbia padana', 'Non si vede più niente nel raggio di un chilometro.'],
  ['Pugno a molla', 'Un guantone da boxe esce da dove meno te lo aspetti.'],
  ['Valanga di neve', 'Una montagna di neve si abbatte sull’arena.'],
  ['Sciame di api', 'Ronzano, pungono, non mollano.'],
  ['Onda anomala', 'Uno tsunami in miniatura travolge tutto.'],
  ['Gigantismo improvviso', 'Diventa alto dieci metri per un minuto.'],
  ['Tempesta di sabbia', 'Sabbia ovunque, negli occhi e nelle scarpe.'],
  ['Colpo del karateka', 'Un colpo che spacca dieci mattoni.'],
  ['Clonazione rapida', 'Tre copie identiche attaccano insieme.'],
  ['Freccia di Cupido', 'L’avversario si innamora di un lampione e si distrae.'],
  // curativi
  ['Brodo della nonna', 'Un sorso di brodo caldo e torna come nuovo.'],
  ['Abbraccio rigenerante', 'Un abbraccio che guarisce ogni livido.'],
  ['Siesta istantanea', 'Trenta secondi di pisolino, cento di energia.'],
  ['Fotosintesi', 'Si mette al sole e si ricarica come una pianta.'],
  ['Risata guaritrice', 'Ride così forte che le ferite si chiudono.'],
  ['Ritorno dal tappeto', 'Una volta per rissa si rialza quando sembrava finita.'],
]

/** Superpoteri che curano invece di colpire (per il narratore di riserva). */
export const MORE_HEALING_POWERS = ['Brodo della nonna', 'Abbraccio rigenerante', 'Siesta istantanea', 'Fotosintesi', 'Risata guaritrice', 'Ritorno dal tappeto']

export const MORE_ARENAS: Row[] = [
  ['Sala d’attesa del dentista', 'Trapani in sottofondo, riviste del 2009, ansia nell’aria.'],
  ['Festa di compleanno per bambini', 'Torta, palloncini, trenta bambini urlanti e un clown stanco.'],
  ['Concerto rock in piazza', 'Casse enormi, pogo, birra che vola.'],
  ['Mercato del pesce di Catania', 'Urla, ghiaccio, pesce spada, pavimento bagnato.'],
  ['Pista da bowling', 'Birilli, palle pesanti, scarpe a noleggio.'],
  ['Parco giochi', 'Scivoli, altalene e una sabbiera infida.'],
  ['Cantiere edile', 'Gru, betoniere, caschi gialli e travi sospese.'],
  ['Nave da crociera', 'Buffet infinito, piscina sul ponte, mare mosso.'],
  ['Grotta preistorica', 'Stalattiti, pitture rupestri e un orso che dorme.'],
  ['Casa infestata', 'Porte che cigolano, fantasmi curiosi, luci che saltano.'],
  ['Campo di calcetto', 'Erba sintetica, porte piccole, amici che litigano.'],
  ['Palestra di quartiere', 'Pesi, specchi, gente che si fa i selfie.'],
  ['Lavanderia a gettoni', 'Lavatrici che girano, calzini spaiati, odore di ammorbidente.'],
  ['Aeroporto con volo cancellato', 'Gente arrabbiata, valigie ovunque, annunci incomprensibili.'],
  ['Planetario', 'Buio, stelle proiettate, poltrone reclinabili.'],
  ['Museo di notte', 'Statue che sembrano guardarti, allarmi sensibilissimi.'],
  ['Fabbrica di cioccolato', 'Fiumi di cioccolato, nastri trasportatori, odore irresistibile.'],
  ['Giungla amazzonica', 'Liane, piranha, umidità al 100%.'],
  ['Polo Nord', 'Ghiaccio, orsi bianchi, venti a meno quaranta.'],
  ['Deserto del Sahara', 'Dune, miraggi, sole che spacca le pietre.'],
  ['Sottomarino', 'Spazi stretti, oblò, un allarme che suona sempre.'],
  ['Sala bingo', 'Cartelle, nonne concentratissime, “ambo!” urlati.'],
  ['Karaoke bar', 'Microfoni, luci colorate, stonati coraggiosi.'],
  ['Tetto di un grattacielo', 'Vento forte, vista mozzafiato, nessuna ringhiera.'],
  ['Giostre della fiera di paese', 'Autoscontri, zucchero filato, tagadà.'],
  ['Stadio tutto esaurito', 'Ottantamila tifosi, cori, fumogeni.'],
  ['Mongolfiera', 'Un cesto di vimini a mille metri d’altezza.'],
  ['Scuola guida', 'Auto con i doppi comandi, istruttore terrorizzato.'],
  ['Sala da tè inglese', 'Porcellane, pasticcini, silenzio educato.'],
  ['Tempio zen', 'Gong, giardino di sabbia, monaci che chiedono silenzio.'],
  ['Cinema durante un film horror', 'Buio, urla, popcorn che volano.'],
  ['Treno del Far West', 'Vagoni di legno, banditi, locomotiva a vapore.'],
  ['Castello medievale', 'Armature, ponte levatoio, fossato con i coccodrilli.'],
  ['Montagne russe', 'Giri della morte, discese a picco, urla.'],
  ['Banca all’ora di chiusura', 'Caveau, allarmi, impiegati che vogliono andare a casa.'],
]

// ---------- mazzi TRAPPOLA: escono solo nel sabotaggio ----------

export const CURSED_WEAPONS: Row[] = [
  ['Piuma di gallina', 'Fa il solletico, nient’altro.'],
  ['Spaghetto crudo', 'Si spezza al primo colpo.'],
  ['Ombrello di carta velina', 'Si strappa con un soffio.'],
  ['Calzino spaiato bagnato', 'Umido, triste, inutile.'],
  ['Spada di cartone fradicia', 'Si piega da sola.'],
  ['Banana sbucciata', 'Si spiaccica. E fa scivolare chi la usa.'],
  ['Cucchiaino da caffè', 'Minuscolo. Mescola bene, colpisce male.'],
  ['Stuzzicadenti singolo', 'Uno solo. E pure spuntato.'],
  ['Palloncino sgonfio', 'Fa “pfff” e basta.'],
  ['Pistola ad acqua scarica', 'Spara aria. A volte nemmeno quella.'],
  ['Zucchero filato', 'Si scioglie appena lo agiti.'],
  ['Foglio A4', 'Al massimo un taglietto. A chi lo impugna.'],
  ['Pantofola di peluche', 'Morbidissima, innocua, a forma di coniglio.'],
  ['Mestolo bucato', 'Non tiene niente, non colpisce niente.'],
  ['Fiore di plastica', 'Decorativo. Solo decorativo.'],
  ['Bolla di sapone', 'Scoppia prima di arrivare.'],
  ['Sassolino', 'Grande come un chicco di riso.'],
  ['Elastico per capelli', 'Schiocca sulle dita di chi lo usa.'],
  ['Coriandolo solitario', 'Uno. Rosa.'],
  ['Lattina vuota', 'Fa rumore, nient’altro.'],
  ['Gelato al sole', 'Si scioglie sulle mani in tre secondi.'],
  ['Pennarello scarico', 'Lascia un segno grigio chiaro.'],
  ['Matita senza punta', 'Inoffensiva e pure brutta.'],
  ['Racchetta senza corde', 'La palla ci passa attraverso.'],
  ['Fischietto rotto', 'Soffi e non esce niente.'],
  ['Biscotto sbriciolato', 'Briciole ovunque, danni nessuno.'],
  ['Spugna da cucina', 'Assorbe, non colpisce.'],
  ['Telecomando senza pile', 'Premi, premi, niente.'],
  ['Cuscino da neonato', 'Morbido come una nuvola. Inutile come una nuvola.'],
  ['Spada di gelatina', 'Trema, si piega, si sbriciola.'],
]

export const CURSED_PERSONALITIES: Row[] = [
  ['Narcolettico', 'Si addormenta di colpo, anche a metà mossa.'],
  ['Pacifista convinto', 'Si rifiuta di fare del male a qualcuno. Anche a chi lo picchia.'],
  ['Codardo totale', 'Scappa appena vede l’avversario.'],
  ['Svenevole', 'Sviene per un niente. Anche per un rumore.'],
  ['Mani di burro', 'Gli scivola di mano tutto, arma compresa.'],
  ['Goffo', 'Inciampa nei propri piedi a ogni passo.'],
  ['Troppo educato', 'Lascia sempre la prima mossa all’altro. E la seconda.'],
  ['Malato immaginario terminale', 'Sicuro di avere poche ore di vita. Combatte steso.'],
  ['Pigro irrecuperabile', 'Si muove solo se costretto. E non è costretto.'],
  ['Fifone del buio', 'Basta un’ombra e si blocca.'],
  ['Distratto dal telefono', 'Guarda le notifiche mentre lo colpiscono.'],
  ['Soffre di vertigini', 'Anche su un gradino gli gira la testa.'],
  ['Innamorato dell’avversario', 'Non riesce a fargli del male. Gli manda bacini.'],
  ['Superstizioso estremo', 'Si blocca davanti a ogni gatto nero, scala o specchio.'],
  ['Panico da palcoscenico', 'Con il pubblico che guarda non riesce a muoversi.'],
  ['Sonnambulo', 'Combatte dormendo. Contro il muro.'],
  ['Lento di riflessi', 'Reagisce ai colpi cinque secondi dopo.'],
  ['Indeciso patologico', 'Ci mette tanto a scegliere che il round finisce.'],
  ['Piagnucoloso', 'Piange a ogni colpo. E anche prima.'],
  ['Arrendevole', 'Al primo graffio alza bandiera bianca.'],
  ['Ingenuo totale', 'Cade in ogni finta, ogni volta.'],
  ['Mammone disperato', 'Chiama la mamma ogni trenta secondi e aspetta risposta.'],
  ['Senza orientamento', 'Attacca sempre dalla parte sbagliata.'],
  ['Brillo di camomilla', 'Barcolla, ride, abbraccia tutti.'],
  ['Timido paralizzato', 'Se lo guardi diventa una statua rossa.'],
  ['Pessimista arreso', 'Ha già deciso di aver perso. Non vede perché combattere.'],
  ['Allergico a tutto', 'Starnuti continui: polvere, polline, avversario.'],
  ['Credulone', 'Crede a tutto quello che gli dice l’avversario.'],
  ['Vanitoso fragile', 'Se si spettina, si ferma a sistemarsi.'],
  ['Nostalgico depresso', 'Pensa solo ai bei tempi e sospira.'],
]

export const CURSED_POWERS: Row[] = [
  ['Invisibile solo a se stesso', 'Non si vede più. Gli altri sì, benissimo.'],
  ['Teletrasporto sbagliato', 'Vuole sparire, ricompare davanti all’avversario.'],
  ['Velocità solo all’indietro', 'Velocissimo, ma solo a marcia indietro.'],
  ['Starnuto incontrollabile', 'Starnutisce a raffica nei momenti peggiori.'],
  ['Diventa un soprammobile', 'Si trasforma in un vaso di ceramica. Fragile.'],
  ['Forza sovrumana nel mignolo', 'Solo nel mignolo. Del piede.'],
  ['Volo rasoterra', 'Vola, a due centimetri da terra.'],
  ['Legge solo il proprio pensiero', 'Sente forte e chiaro solo i suoi dubbi.'],
  ['Parla con i sassi', 'I sassi ascoltano, ma non rispondono.'],
  ['Si trasforma in una papera', 'Per un minuto è una papera. Qua.'],
  ['Calamita per i colpi', 'Ogni colpo nel raggio di dieci metri finisce su di lui.'],
  ['Laser di ritorno', 'Il raggio laser parte dagli occhi e torna indietro.'],
  ['Nuvoletta personale', 'Una nuvola gli piove addosso. Solo a lui.'],
  ['Profezia sbagliata', 'Vede il futuro. Sbaglia sempre.'],
  ['Diventa minuscolo', 'Alto cinque centimetri. Per sempre? Speriamo di no.'],
  ['Tempo fermo, tranne l’avversario', 'Ferma il tempo per tutti, l’avversario escluso.'],
  ['Fa ridere l’avversario', 'L’avversario ride così tanto che recupera le forze.'],
  ['Colore a caso', 'Cambia colore. Nient’altro.'],
  ['Opera inarrestabile', 'Si mette a cantare l’opera e non riesce a smettere.'],
  ['Immune al solletico', 'Un superpotere. Più o meno.'],
  ['Orecchie elastiche', 'Si allungano solo le orecchie. Ci inciampa.'],
  ['Clone pigro', 'Il suo clone si siede e guarda.'],
  ['Scudo di vetro sottile', 'Si incrina guardandolo.'],
  ['Udito insopportabile', 'Sente tutto amplificato mille volte. Anche i suoi passi.'],
  ['Comanda le zanzare', 'Le zanzare obbediscono. Pungono lui.'],
  ['Gravità doppia', 'Pesa il doppio. Solo lui.'],
  ['Si scioglie col caldo', 'Come un ghiacciolo ad agosto.'],
  ['Lampadina della bugia', 'Una lampadina in testa si accende quando bluffa.'],
  ['Pelle di gelatina', 'Trema a ogni passo, si ammacca a ogni colpo.'],
  ['Evoca il vicino rompiscatole', 'Arriva il vicino a lamentarsi. Con lui.'],
]
